services:
  portainer:
    image: portainer/portainer-ce:2.29.0-alpine
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Madrid
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
    restart: always

volumes:
  portainer_data:
  nodered_data: